INSERT INTO `EMPRESA` (`ID`, `CNPJ`, `DATA_ATUALIZACAO`, `DATA_CRIACAO`, `RAZAO_SOCIAL`)
VALUES (NULL, '82198127000121', CURRENT_DATE(), CURRENT_DATE(), 'EmpresaTeste');

INSERT INTO `FUNCIONARIO` (`ID`, `CPF`, `DATA_ATUALIZACAO`, `DATA_CRIACAO`, `EMAIL`, `NOME`, 
`PERFIL`, `QTD_HORAS_ALMOCO`, `QTD_HORAS_TRABALHO_DIA`, `SENHA`, `VALOR_HORA`, `EMPRESA_ID`)
VALUES (NULL, '16248890935', CURRENT_DATE(), CURRENT_DATE(), 'admin@admin.com', 'ADMIN', 'ROLE_ADMIN', 
NULL, NULL, '$2a$10$D2x3VKWkLRnXLD2GZg74fOpLI1Q/MAR99WrcnVSubSq7HalZUZieq', NULL, 
(SELECT `ID` FROM `EMPRESA` WHERE `CNPJ` = '82198127000121'));